package com.inventory.backend.entity;

public enum ActionLogType {
    CARTRIDGE_CREATED,
    CARTRIDGE_QUANTITY_CHANGED,
    CARTRIDGE_INSTALLED,
    CARTRIDGE_REMOVED,
    CARTRIDGE_SENT_TO_REFILL,
    CARTRIDGE_RETURNED_FROM_REFILL,
    CARTRIDGE_WRITTEN_OFF,
    CARTRIDGE_MARKED_EMPTY,
    CARTRIDGE_REFILLABLE_CHANGED,
    CARTRIDGE_DELETED,
    DEPARTMENT_CREATED,
    DEPARTMENT_UPDATED,
    DEPARTMENT_DELETED,
    CARTRIDGE_MODEL_CREATED,
    CARTRIDGE_MODEL_DELETED
}
