ALTER TABLE printers
    ADD COLUMN IF NOT EXISTS model VARCHAR(255),
    ADD COLUMN IF NOT EXISTS ip_address VARCHAR(64),
    ADD COLUMN IF NOT EXISTS serial_number VARCHAR(255),
    ADD COLUMN IF NOT EXISTS device_type VARCHAR(32) NOT NULL DEFAULT 'PRINTER',
    ADD COLUMN IF NOT EXISTS status VARCHAR(32) NOT NULL DEFAULT 'IN_OPERATION',
    ADD COLUMN IF NOT EXISTS commissioned_at DATE,
    ADD COLUMN IF NOT EXISTS written_off_at DATE,
    ADD COLUMN IF NOT EXISTS comment VARCHAR(1000);

UPDATE printers
SET written_off_at = CURRENT_DATE
WHERE status = 'WRITTEN_OFF' AND written_off_at IS NULL;
