spring.application.name=backend

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/cartridge_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:cartridge_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:cartridge_pass}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

server.port=${SERVER_PORT:8080}
